FRASES = [
    "Você é capaz de mais do que imagina.",
    "Um passo por dia já é progresso.",
    "Acredite no processo.",
    "Pequenas ações geram grandes resultados.",
    "Nunca é tarde para recomeçar.",
    "Disciplina vence a motivação.",
    "Seu esforço vai valer a pena.",
    "Continue — você já chegou longe demais para voltar.",
    "Um dia de cada vez.",
    "Faça o seu melhor hoje.",
    "Só para quem não desiste.",
    "Persistência constrói resultados.",
    "Você está evoluindo, mesmo que não perceba.",
    "Foque no que você pode controlar.",
    "Coragem é continuar mesmo com medo.",
    "Nada muda se você não mudar.",
    "Seja constante, não perfeito.",
    "Pequenos hábitos, grandes conquistas.",
    "Apenas comece. O resto se ajeita.",
    "A melhor hora é agora.",
    "Você consegue.",
    "O sucesso começa no esforço diário.",
    "Errar faz parte do caminho.",
    "Celebre cada pequena vitória.",
    "O importante é não parar.",
    "Escolha avançar.",
    "A constância constrói futuros.",
    "Não compare seu capítulo 1 com o capítulo 20 de alguém.",
    "Você está no caminho certo.",
    "Transforme intenção em ação."
]
